### ISSUE TITLE
Error plotting figure in module

### ISSUE THREAD

**Issue by andrew-edwards** [quantitative-biology/module-4-machine#3]
Fresh build (updating all repos), I get:
```
Attaching package: 'neuralnet'
The following object is masked from 'package:dplyr':
    compute

Quitting from lines 3676-3694 (_main.Rmd) 
Error in t.default(net$result.matrix) : argument is not a matrix
```

Narrowed the error down to:
```
> plot(nniris, rep="best", information=FALSE, intercept=FALSE)
Error in t.default(net$result.matrix) : argument is not a matrix
```
I do get:
```
> nniris <- neuralnet(Species ~ Petal.Width + Petal.Length, iristrain, hidden=3,linear.output = FALSE, algorith='backprop', learningrate = 0.01)
Warning message:
Algorithm did not converge in 1 of 1 repetition(s) within the stepmax. 
```
so wonder if that's the problem. 

Also, probably want to change `compute()` to `neuralnet::compute()` given the masking warning. I thought that's what was giving the error and would be an easy fix, but alas not. The error occurs just beforehand.

I can just comment out the module to get building for me, just wanted to let you know (and so others can run the code).

**Comment by kcudding** [comment]
I'm not able to replicate

**Comment by andrew-edwards** [comment]
If I set `stepmax = 1e06` in `nniris <- neuralnet(....)` then I don't get the warning. And the plot (and the rest) works:

![image](https://user-images.githubusercontent.com/6977190/155422415-059399e1-3fcb-41ca-8667-c1f0a83b5bc6.png)

Not sure if those results agree with yours? Just sounds like it needs a big stepsize to get somewhere at the start? Maybe.....

**Comment by kcudding** [comment]
presumably every once in a while it won't converge

**Comment by kcudding** [comment]
weights are quite different, but then no idea how stable the model is. BTW this is not from the .rmd, not formatted?

**Comment by kcudding** [comment]
I just saw it ... when I changed compute to neuralnet::compute.... then it disappeared when I changed it back

**Comment by andrew-edwards** [comment]
From the .rmd. No big worry for me now I have it (almost) working (I won't push my fix). More of a heads up if anyone else tries it.

**Comment by kcudding** [comment]
My point is that if that is from the .rmd, then there is a problem since it doesn't seem to have the most recent formatting 

#rounding the weight values so the plot is tidier
nniris$weights[[1]] <- lapply(nniris$weights[[1]], function(x) round(x, 1))

#plotting the neural net (but not the intercepts or error rates)
plot(nniris, rep="best", information=FALSE, intercept=FALSE)

?

**Comment by kcudding** [comment]
and I dimly recall a package conflict that was subsequently resolved...

**Comment by kcudding** [comment]
pushed neuralnet::compute

**Comment by andrew-edwards** [comment]
Not sure what you mean by formatting. I have the same code as you pasted (plus more plus comments, but it all looks the same). Anyway, am commenting out anyway to speed up (I didn't see a cache getting built, but don't worry).

**Comment by kcudding** [comment]
the rounding on the weights (numbers on the graph) is not there, that's why I wondered if you had the most recent version

**Comment by andrew-edwards** [comment]
Strange. I fetched all modules and Basics today.

**Comment by kcudding** [comment]
I had to revert to an earlier commit, maybe that creates an issue?

**Comment by kcudding** [comment]
still cannot replicate

**Comment by andrew-edwards** [comment]
Don't worry. Just something to be aware of in case anyone else tries to run the code and gets similar differences.
